Repository IBM/crossplane-provider-kubernetes, pull requests merged in 2022-01, with the labels that each got.

#8 CatalogSource building script
  .github/workflows/backport.yml
  .github/workflows/catsrc.yaml
  .github/workflows/commands.yml
  common/Makefile.operator.mk
  common/scripts/build_catsrc.sh
  common/scripts/install_tools.sh
Labels: size/XL

#10 Certification
  bundle.Dockerfile
  bundle/manifests/crossplane-provider-kubernetes-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/adjust_manifests.sh
Labels: size/XS

#13 Fix roles
  .github/workflows/ci.yml
  bundle/manifests/crossplane-provider-kubernetes-operator.clusterserviceversion.yaml
  bundle/manifests/ibm-crossplane-provider-kubernetes-ibm-crossplane_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/ibm-crossplane-provider-kubernetes-ibm-crossplane_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  common/scripts/build_catsrc.sh
  config/manifests/bases/crossplane-provider-kubernetes-operator.clusterserviceversion.yaml
  config/rbac/ibm-crossplane_clusterrole.yaml
  config/rbac/ibm-crossplane_clusterrole_binding.yaml
  config/rbac/kustomization.yaml
Labels: size/M

#14 change project name
  PROJECT
  bundle.Dockerfile
  bundle/manifests/ibm-crossplane-provider-kubernetes-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  cluster/images/provider-kubernetes-controller/Makefile
  common/Makefile.operator.mk
  common/scripts/adjust_manifests.sh
  common/scripts/build_catsrc.sh
  common/scripts/lint-csv.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-crossplane-provider-kubernetes-operator.clusterserviceversion.yaml
  ibm/Makefile.common.mk
  package/crossplane.yaml
Labels: size/M

#15 Fix dockerfile
  .github/workflows/catsrc.yaml
  cluster/images/provider-kubernetes/Dockerfile
Labels: size/XS

#16 Fix replaces
  bundle/manifests/ibm-crossplane-provider-kubernetes-operator.clusterserviceversion.yaml
  common/scripts/adjust_manifests.sh
Labels: size/XS

#17 fix package names in build_catsrc.sh
  common/scripts/build_catsrc.sh
Labels: size/XS

#18 Fix catsrc action
  .github/workflows/catsrc.yaml
  common/scripts/build_catsrc.sh
Labels: size/S

#20 add annotation to hide operator
  bundle/manifests/ibm-crossplane-provider-kubernetes-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-crossplane-provider-kubernetes-operator.clusterserviceversion.yaml
Labels: size/XS

#21 Copyright date update
  .github/workflows/catsrc.yaml
  Makefile
  cluster/images/provider-kubernetes-controller/Makefile
  cluster/images/provider-kubernetes/Makefile
  common/Makefile.common.mk
  common/Makefile.operator.mk
  common/scripts/adjust_manifests.sh
  common/scripts/build_catsrc.sh
  common/scripts/config_docker.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/install_tools.sh
  common/scripts/lint-csv.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/update_catalogsource.sh
  common/scripts/update_global_pull_secrets.sh
  ibm/Makefile.common.mk
Labels: size/M
