Repository IBM/crossplane-provider-kubernetes, pull requests merged in 2022-02, with the labels that each got.

#22 fix annotations for hidden operators
  bundle/manifests/ibm-crossplane-provider-kubernetes-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-crossplane-provider-kubernetes-operator.clusterserviceversion.yaml
Labels: size/XS

#23 Update release version
  PREVIOUS_VERSION
  RELEASE_VERSION
  bundle/manifests/ibm-crossplane-provider-kubernetes-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-crossplane-provider-kubernetes-operator.clusterserviceversion.yaml
Labels: size/S

#24 change to read from configmap
  cmd/provider/main.go
  common/scripts/build_catsrc.sh
Labels: size/M

#27 change hardcoded namespace to env variable
  cmd/provider/main.go
Labels: size/XS

#29 revert permissions by removing rbac for Crossplane
  bundle/manifests/ibm-crossplane-provider-kubernetes-ibm-crossplane_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/ibm-crossplane-provider-kubernetes-ibm-crossplane_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  config/rbac/ibm-crossplane_clusterrole.yaml
  config/rbac/ibm-crossplane_clusterrole_binding.yaml
  config/rbac/kustomization.yaml
Labels: size/M

#30 Update release version
  PREVIOUS_VERSION
  RELEASE_VERSION
  bundle/manifests/ibm-crossplane-provider-kubernetes-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-crossplane-provider-kubernetes-operator.clusterserviceversion.yaml
Labels: size/S, lgtm

#32 update go to 1.17.7
  .github/workflows/catsrc.yaml
Labels: size/XS, lgtm
