Repository IBM/crossplane-provider-kubernetes, pull requests merged in 2023-01, with the labels that each got.

#66 update go version
  .github/workflows/catsrc.yaml
  .github/workflows/ci.yml
Labels: size/XS

#67 add bump version script
  bump-version.py
Labels: size/L

#68 Update 1.8.7
  PREVIOUS_VERSION
  RELEASE_VERSION
  bump-version.py
  bundle/manifests/ibm-crossplane-provider-kubernetes-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-crossplane-provider-kubernetes-operator.clusterserviceversion.yaml
Labels: size/L

#65 add vcs labels
  cluster/images/provider-kubernetes-controller/Dockerfile
  cluster/images/provider-kubernetes-controller/Makefile
Labels: size/M

#69 set labels values
  cluster/images/provider-kubernetes-controller/Makefile
Labels: size/XS

#70 update-copyrights-2023
  .github/workflows/catsrc.yaml
  Makefile
  cluster/images/provider-kubernetes-controller/Makefile
  cluster/images/provider-kubernetes/Makefile
  common/Makefile.common.mk
  common/Makefile.operator.mk
  common/scripts/adjust_manifests.sh
  common/scripts/build_catsrc.sh
  common/scripts/config_docker.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/install_tools.sh
  common/scripts/lint-csv.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/update_catalogsource.sh
  common/scripts/update_global_pull_secrets.sh
  ibm/Makefile.common.mk
  ibm/scripts/config_docker.sh
Labels: size/M

#73 Updated registry endpoint
  .github/workflows/catsrc.yaml
  Makefile
  common/Makefile.operator.mk
  common/scripts/build_catsrc.sh
  common/scripts/config_docker.sh
  common/scripts/update_global_pull_secrets.sh
  ibm/Makefile.common.mk
  ibm/scripts/config_docker.sh
Labels: size/M
